name: Publish services

on: 
  workflow_dispatch:
  push:
    branches:
    - dev
    - github-actions
  pull_request:
    branches:
    - dev
    - github-actions

jobs:
  publish-api:
    runs-on: ubuntu-latest
    
    env:
      SOLUTION_PATH: ./Voluncare.Server.API/Voluncare.Managment/Voluncare.Managment.sln
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-versions: '6.0.x'
      
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}
        
      - name: Build 
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
      
      - name: Publish 
        run: dotnet publish ${{ env.SOLUTION_PATH }} --configuration Release --no-build
        
      
          
        
          
