name: CI/CD

on: 
  workflow_dispatch:
  push:
    branches:
    - dev
    - github-actions
  pull_request:
    branches:
    - dev
    - github-actions

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
  test-all:
    uses: ./.github/workflows/run_tests.yml

  publish-api:
    needs: test-all
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/publish_to_azure_app.yml
    with: 
      docker_file_path: ./Voluncare.Server.API/Voluncare.Managment
      docker_image_name: voluncare-api
      tag: ${{ github.sha }}  #'develop-${GITHUB_RUN_NUMBER}'
    secrets: 
      registry_login_server: voluncare.azurecr.io
      registry_username: voluncare
      registry_password: ps6bysqP8uzX2rznSxuyKyec1GXzQnbq4SD9Focp7e+ACRBmTVwZ
      azure_webapp_publish_profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

  publish-ui:
    needs: test-all
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/publish_to_azure_app.yml
    with: 
      docker_file_path: ./Frontend
      docker_image_name: voluncare-ui
      tag: ${{ github.sha }} #'develop-${GITHUB_RUN_NUMBER}'
    secrets: 
      registry_login_server: voluncare.azurecr.io
      registry_username: voluncare
      registry_password: ps6bysqP8uzX2rznSxuyKyec1GXzQnbq4SD9Focp7e+ACRBmTVwZ
      azure_webapp_publish_profile: ${{ secrets.AZURE_WEBAPP_UI_PUBLISH_PROFILE }}
