name: Publish services

on: 
  workflow_dispatch:
  push:
    branches:
    - dev
    - github-actions
  pull_request:
    branches:
    - dev
    - github-actions

jobs:
  publish-api:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_FILE_PATH: ./Voluncare.Server.API/Voluncare.Managment/Dockerfile
      SOLUTION_PATH: ./Voluncare.Server.API/Voluncare.Managment/Voluncare.Managment.sln
      REGISTRY_LOGIN_SERVER: voluncare.azurecr.io
      REGISTRY_USERNAME: voluncare
      REGISTRY_PASSWORD: ps6bysqP8uzX2rznSxuyKyec1GXzQnbq4SD9Focp7e+ACRBmTVwZ
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Clear Docker
        run: docker system prune -af
#       - name: Setup .NET
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-versions: '6.0.x'
      
#       - name: Restore
#         run: dotnet restore ${{ env.SOLUTION_PATH }}
        
#       - name: Build 
#         run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
      
#       - name: Publish 
#         run: dotnet publish ${{ env.SOLUTION_PATH }} --configuration Release --no-build

      - name: 'Docker Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Push Docker image to Azure Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY_USERNAME }}/voluncare-api:${{ github.sha }}
          file: ${{ env.DOCKER_FILE_PATH }}
          
        
          
