name: Publish docker image to azure app

on:
  workflow_call:
    inputs:
      docker_file_path:
        required: true
        type: string
      docker_image_name:
        required: true
        type: string
    secrets: 
      registry_login_server:
        required: true
      registry_username:
        required: true
      registry_password:
        required: true
      azure_webapp_publish_profile:
        required: true

jobs:
  publish-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker Image
        run: docker build ${{ inputs.docker_file_path }} -t ${{ secrets.registry_login_server }}/${{ inputs.docker_image_name }}:latest  
        
      - name: Tag Docker Image
        run: docker tag ${{ secrets.registry_login_server }}/${{ inputs.docker_image_name }}:latest ${{ secrets.registry_login_server }}/${{ inputs.docker_image_name }}:${{ github.sha }}
        
      - name: 'Docker Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.registry_login_server }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}
  
      - name: Build and Push Docker Image
        run: docker push ${{ secrets.registry_login_server }}/${{ inputs.docker_image_name }}:${{ github.sha }}
      
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'voluncare-api'
          publish-profile: ${{ secrets.azure_webapp_publish_profile }}
          images: ${{ secrets.registry_login_server  }}/${{ inputs.docker_image_name }}:${{ github.sha }}